# Datasource configuration
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/PP_BTB_DB
    username: postgres
    password: 1234
server:
     port: 8181